### ISSUE TITLE
Reading sender address balance failed

### ISSUE THREAD

**Issue by 4pe4ll** [mnedelchev-vn/pancakeswap-sniper-bot#10]
![image](https://user-images.githubusercontent.com/88870420/129302572-8f4a5896-6e2b-4ed0-a253-949442d81a18.png)

I already put in the private key with 0x, but it unable to read my balance.

**Comment by mnedelchev-vn** [comment]
It's very likely that this was temporary issue, because the bot is running with external blockchain node. Nodes sometimes can go down for few minutes or hours. However if the issue still exists then copy and paste your bot command here ( without your private key ) so I can check if you're doing something wrong.

I will close the issue if you do not respond within one week.

**Comment by annhan** [comment]
good bot.. thanks for share.. Are you from Viet Nam ?

**Comment by 4pe4ll** [comment]
I still having same error. Here is my command

pm2 start pancakeswap-sniper-bot.js -- tokenAddress=0x917841c010b3d86ed886f36f2c9807e07a2e3093 buyingBnbAmount=0.05 senderPrivateKey=0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx createLogs=true gasPrice=25 transactionSlippage=30 bscNetwork=mainnet

**Comment by 4pe4ll** [comment]
0xc5d8c87f97cd2b33255be416019db4de96b8afdb

is this your wallet?

**Comment by 4pe4ll** [comment]
Is a scam, don't every try to use this shit...your wallet will get drain

**Comment by mnedelchev-vn** [comment]
@4pe4ll I'm sorry for you loss, but don't blame me or my bot for you getting scammed. Anyone who knows something about programming can check the code and see that private key of users is safe ( there're not any requests sending the private key outside of the bot ). Many other people are using the bot for month now without issues, you should think where you have placed this private key beside my bot.

And no, this is not my wallet.
