### ISSUE TITLE
estimateGas() failed error 

### ISSUE THREAD

**Issue by badlog101** [mnedelchev-vn/pancakeswap-sniper-bot#9]
![image](https://user-images.githubusercontent.com/19583198/129283006-4c991db9-1ab4-4880-bda7-a253fe9b4714.png)

Hello, I am getting this error when trying to snipe certain tokens. Otherwise the bot works pretty well. I have tested all sorts of gas limit, slippage, and gas price settings, same error, only on certain tokens. Even well after the liq has been added, same error.

**Comment by mnedelchev-vn** [comment]
This might be happening, because you're trying to buy too much while there is condition in the token contract which is stopping this. By the time of pancakeswap listing most of the projects are setting **max buy limit** for few minutes or hours in order to prevent bots buying big amounts. And this is why the bot has ``transactionIterations`` option which is basically helping you to execute many transactions with small buy amounts at the same time. You're paying more in fees, but you're still able to buy early.

**Comment by badlog101** [comment]
I understand the functionality of a max buy limit, but this wasn't the case in my testing. I have used very small buy amounts to test (0.0002bnb), and I have tested a transaction hours after launch. Same result, only on certain contracts.
